services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springboot-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: springboot-backend
    ports:
      - "8080:8080"
    volumes:
        - ./backend:/app
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres-data: